# Generated by Django 2.1.7 on 2019-03-17 14:12

import computed_property.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bmi',
            field=computed_property.fields.ComputedIntegerField(blank=True, compute_from='get_bmi', editable=False, null=True),
        ),
    ]
