# Generated by Django 2.1.7 on 2019-03-17 14:39

import computed_property.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_bmi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=computed_property.fields.ComputedIntegerField(blank=True, compute_from='getAge', editable=False, null=True),
        ),
    ]
