# Generated by Django 2.1.7 on 2019-03-17 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190317_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bloodtype',
            field=models.CharField(blank=True, choices=[('a', 'A'), ('b', 'B'), ('ab', 'AB'), ('o', 'O')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='dci',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
