# Generated by Django 2.1.7 on 2019-03-19 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190317_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='useractivity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
