# Generated by Django 2.1.7 on 2019-03-20 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_useractivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklist',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diseases', to='core.Disease'),
        ),
        migrations.AlterField(
            model_name='blacklist',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='core.Food'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis', to='core.Disease'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to=settings.AUTH_USER_MODEL),
        ),
    ]
