# Generated by Django 2.1.7 on 2019-03-20 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190320_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosis',
            name='disease',
        ),
        migrations.RemoveField(
            model_name='diagnosis',
            name='user',
        ),
        migrations.RemoveField(
            model_name='food',
            name='bloodtype',
        ),
        migrations.DeleteModel(
            name='Diagnosis',
        ),
    ]
