# Generated by Django 2.1.7 on 2019-03-21 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190320_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='img',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
