# Generated by Django 2.1.7 on 2019-05-16 12:20

import computed_property.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20190321_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=computed_property.fields.ComputedIntegerField(compute_from='get_age', editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='bloodtype',
            field=models.CharField(choices=[('a', 'A'), ('b', 'B'), ('ab', 'AB'), ('o', 'O')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='bmi',
            field=computed_property.fields.ComputedIntegerField(compute_from='get_bmi', editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='dci',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='useractivity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='weight',
            field=models.IntegerField(null=True),
        ),
    ]
